# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Laura Dijkhuizen
email: laura.w.dijkhuizen@gmail.com
description: 
  Home page of Laura Dijkhuizen; scientist in training. Working as plant biologist on the Azolla metagenome.
twitter_username: lauraazolla
github_username: lauralwd
minimal_mistakes_skin: contrast
search: false #search: true
repository: lauralwd/lauralwd.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-DYW605XPMV"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Laura Dijkhuizen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD candidate at Utrecht University. Working on plant biology & metagenomics of Azolla ferns and their symbiosis with cyanobacteria"
  links:
    - label: "Utrecht University page"
      icon: "fas fa-fw fa-university"
      url: "https://www.uu.nl/medewerkers/lwdijkhuizen/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lauradijkhuizen/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LauraLWD"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-4628-7671"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/LauraDijkhuizen/featured"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/LauraAzolla"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/laura_in_utrecht/"
    - label: "Google scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=p6QyHVYAAAAJ&hl=en"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/LauraAzolla"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LauraLWD"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/laura_in_utrecht"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-4628-7671"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
 # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
